version: '3.5'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: good-management
    environment:
      - DATABASE_HOST=${DATABASE_HOST} #'db' вместо localhost
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - JWT_ACCESS_EXPIRESIN=${JWT_ACCESS_EXPIRESIN}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_EXPIRESIN=${JWT_REFRESH_EXPIRESIN}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - COOKIE_EXPIRESIN=${COOKIE_EXPIRESIN}
      - NODE_ENV=${NODE_ENV}
      - UPLOADS_PATH=/static/uploads
      - BUILD_PATH=/static/frontend/build
    ports:
      - '5000:5000'
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads  # Монтирование папки uploads
      - /root/gm_front_build/GM:/static/frontend/build  # Монтирование папки с фронтендом

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbit_data:/var/lib/rabbitmq
    restart: always
    ports:
      - '5672:5672' # AMQP порт
      - '15672:15672' # Порт для управления через веб-интерфейс

  redis:
    container_name: cache
    image: redis
    volumes:
      - ./redis_data:/var/lib/redis
    environment:
      - REDIS_HOST_LOCAL=${REDIS_HOST_LOCAL}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD:=${REDIS_PASSWORD}
    ports:
      - 6379:6379
