import { MigrationInterface, QueryRunner } from "typeorm";

export class ResultUnionMigration1748959506558 implements MigrationInterface {
    name = 'ResultUnionMigration1748959506558'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "refresh_session" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_agent" character varying(200) NOT NULL, "fingerprint" character varying(200) NOT NULL, "ip" character varying NOT NULL, "expiresIn" integer NOT NULL, "refreshToken" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_5d0d8c21064803b5b2baaa50cbb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "policy_directory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "directoryName" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "accountId" uuid NOT NULL, CONSTRAINT "PK_f825c892fc452f3847a120bfe82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "policy_to_policy_directory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "policyId" uuid, "policyDirectoryId" uuid, CONSTRAINT "PK_39a754a55ebd3faffd57980acb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_247be4c1647471cd372ca759a6" ON "policy_to_policy_directory" ("policyId") `);
        await queryRunner.query(`CREATE TABLE "target_holder" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "targetId" uuid NOT NULL, "postId" uuid NOT NULL, CONSTRAINT "PK_be0687cc758ff63787237a40a14" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5b7a1399bb79f0a6f817e2629" ON "target_holder" ("targetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe119993b527196cf2e85fd172" ON "target_holder" ("postId") `);
        await queryRunner.query(`CREATE TABLE "objective" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "situation" text array, "content" text array, "rootCause" text array, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "strategyId" uuid NOT NULL, "accountId" uuid NOT NULL, CONSTRAINT "REL_3b9f2b0b950b992feb67e225e3" UNIQUE ("strategyId"), CONSTRAINT "PK_1084365b2a588160b31361a252e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3b9f2b0b950b992feb67e225e3" ON "objective" ("strategyId") `);
        await queryRunner.query(`CREATE TYPE "public"."strategy_state_enum" AS ENUM('Черновик', 'Активный', 'Завершено')`);
        await queryRunner.query(`CREATE TABLE "strategy" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "strategyNumber" integer NOT NULL, "dateActive" TIMESTAMP, "content" text NOT NULL, "state" "public"."strategy_state_enum" NOT NULL DEFAULT 'Черновик', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postCreatorId" uuid NOT NULL, "accountId" uuid NOT NULL, "organizationId" uuid, CONSTRAINT "PK_733d2c3d4a73c020375b9b3581d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."project_type_enum" AS ENUM('Проект', 'Программа')`);
        await queryRunner.query(`CREATE TABLE "project" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectNumber" integer NOT NULL, "projectName" character varying(50) NOT NULL DEFAULT 'Проект', "programId" uuid, "content" text, "type" "public"."project_type_enum" NOT NULL DEFAULT 'Проект', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organizationId" uuid, "strategyId" uuid, "accountId" uuid NOT NULL, "postCreatorId" uuid NOT NULL, CONSTRAINT "PK_4d68b1358bb5b766d3e78f32f57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b27ea5389a49df32d110a00b0f" ON "project" ("strategyId") `);
        await queryRunner.query(`CREATE TABLE "message_seen_status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timeSeen" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "messageId" uuid NOT NULL, "postId" uuid NOT NULL, CONSTRAINT "PK_78fc09fa004973ad15589ed890b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "messageNumber" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "convertId" uuid NOT NULL, "senderId" uuid NOT NULL, CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attachment_to_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "attachmentId" uuid, "messageId" uuid, CONSTRAINT "PK_b7ec8eb0d10a38ff3d1a3025f32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_13f0723c85fbc64fb393065df6" ON "attachment_to_message" ("attachmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f816633bad04a76f3a96495ddf" ON "attachment_to_message" ("messageId") `);
        await queryRunner.query(`CREATE TABLE "attachment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "attachmentName" character varying(255) NOT NULL, "attachmentPath" character varying NOT NULL, "attachmentSize" integer NOT NULL, "attachmentMimetype" character varying NOT NULL, "hash" character varying NOT NULL, "originalName" character varying NOT NULL DEFAULT 'OriginalName', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d2a80c3a8d467f08a750ac4b420" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attachment_to_target" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "attachmentId" uuid, "targetId" uuid, CONSTRAINT "PK_5439fec9d12b0e1cb2b481f9bf1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6aacb469923096e42216b9ba22" ON "attachment_to_target" ("attachmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ebf12db8fd34879e66590fea2" ON "attachment_to_target" ("targetId") `);
        await queryRunner.query(`CREATE TYPE "public"."target_type_enum" AS ENUM('Задача', 'Метрика', 'Правила', 'Продукт', 'Организационные мероприятия', 'Приказ', 'Личная')`);
        await queryRunner.query(`CREATE TYPE "public"."target_targetstate_enum" AS ENUM('Черновик', 'Активная', 'Отменена', 'Завершена')`);
        await queryRunner.query(`CREATE TABLE "target" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."target_type_enum" NOT NULL DEFAULT 'Задача', "orderNumber" integer NOT NULL, "content" text NOT NULL, "holderPostId" uuid, "targetState" "public"."target_targetstate_enum" NOT NULL DEFAULT 'Черновик', "dateStart" TIMESTAMP, "deadline" TIMESTAMP, "dateComplete" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "convertId" uuid, "projectId" uuid, "policyId" uuid, CONSTRAINT "REL_c32ec30acb8104bda79376f3af" UNIQUE ("convertId"), CONSTRAINT "PK_9d962204b13c18851ea88fc72f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b417a52ac7f5278f81327dfa86" ON "target" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e4be9fdeee9449f164f5dc44b" ON "target" ("policyId") `);
        await queryRunner.query(`CREATE TYPE "public"."policy_state_enum" AS ENUM('Черновик', 'Активный', 'Отменён')`);
        await queryRunner.query(`CREATE TYPE "public"."policy_type_enum" AS ENUM('Директива', 'Инструкция', 'Распоряжение')`);
        await queryRunner.query(`CREATE TABLE "policy" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "policyName" character varying NOT NULL, "policyNumber" integer NOT NULL, "state" "public"."policy_state_enum" NOT NULL DEFAULT 'Черновик', "type" "public"."policy_type_enum" NOT NULL DEFAULT 'Директива', "dateActive" TIMESTAMP, "deadline" TIMESTAMP, "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postCreatorId" uuid NOT NULL, "organizationId" uuid, "accountId" uuid NOT NULL, CONSTRAINT "PK_9917b0c5e4286703cc656b1d39f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."statistic_data_correlationtype_enum" AS ENUM('Месяц', 'Год', 'Неделя')`);
        await queryRunner.query(`CREATE TABLE "statistic_data" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "value" numeric NOT NULL, "valueDate" TIMESTAMP NOT NULL DEFAULT now(), "correlationType" "public"."statistic_data_correlationtype_enum", "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "statisticId" uuid, CONSTRAINT "PK_843497079685d8d08e6b701c6c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."control_panel_paneltype_enum" AS ENUM('Глобальная', 'Личная')`);
        await queryRunner.query(`CREATE TYPE "public"."control_panel_graphtype_enum" AS ENUM('Ежегодовой', '13', '26', '52', 'Ежемесячный', 'Ежедневный')`);
        await queryRunner.query(`CREATE TABLE "control_panel" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "panelName" character varying(255) NOT NULL DEFAULT 'Панель №', "orderNumber" integer NOT NULL, "controlPanelNumber" integer NOT NULL, "panelType" "public"."control_panel_paneltype_enum" NOT NULL DEFAULT 'Личная', "graphType" "public"."control_panel_graphtype_enum" NOT NULL DEFAULT 'Ежедневный', "isNameChanged" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organizationId" uuid, "postId" uuid, CONSTRAINT "PK_5b7d73568d4db8993fe32913b93" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "panel_to_statistic" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderStatisticNumber" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "controlPanelId" uuid NOT NULL, "statisticId" uuid NOT NULL, CONSTRAINT "PK_6a97bbed21f3dd117e1c653ec1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7b4fbbcc0a5cb0fcb2d1041141" ON "panel_to_statistic" ("controlPanelId") `);
        await queryRunner.query(`CREATE TYPE "public"."statistic_type_enum" AS ENUM('Прямая', 'Обратная')`);
        await queryRunner.query(`CREATE TABLE "statistic" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."statistic_type_enum" NOT NULL DEFAULT 'Прямая', "name" text NOT NULL, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postId" uuid, "accountId" uuid NOT NULL, CONSTRAINT "PK_e3e6fd496e1988019d8a46749ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "history_users_to_post" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postId" uuid, "userId" uuid, CONSTRAINT "PK_b7b268cb7fe524cdce6ad47264f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f2d3568f244296ce211306dd24" ON "history_users_to_post" ("postId") `);
        await queryRunner.query(`CREATE TABLE "convert_to_post" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postId" uuid, "convertId" uuid, CONSTRAINT "UQ_ab65d4f74f77c0a2fef3c282075" UNIQUE ("postId", "convertId"), CONSTRAINT "PK_7d85995785f6e182efb13a8199e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "groupName" character varying(50) NOT NULL, "groupDivisionName" character varying(50), "groupNumber" SERIAL NOT NULL, "groupAvatarUrl" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "accountId" uuid NOT NULL, CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_to_post" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postId" uuid, "groupId" uuid, CONSTRAINT "PK_3d3b7b25fb96af76a064e98e5c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4f9121b07f10f2cf2f07beee5" ON "group_to_post" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d84c384f4967eca67b658c339" ON "group_to_post" ("groupId") `);
        await queryRunner.query(`CREATE TYPE "public"."role_setting_module_enum" AS ENUM('policy', 'goal', 'objective', 'strategy', 'project', 'post', 'statistic')`);
        await queryRunner.query(`CREATE TABLE "role_setting" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "module" "public"."role_setting_module_enum" NOT NULL, "can_read" boolean NOT NULL DEFAULT true, "can_create" boolean NOT NULL DEFAULT false, "can_update" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "roleId" uuid, "accountId" uuid NOT NULL, CONSTRAINT "PK_d95dd723687e9e68b1d6ed9f8de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."role_rolename_enum" AS ENUM('Собственник', 'Админ', 'Помощник', 'Директор', 'Руководитель', 'Сотрудник')`);
        await queryRunner.query(`CREATE TABLE "role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roleName" "public"."role_rolename_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "goal" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text array NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postCreatorId" uuid NOT NULL, "accountId" uuid NOT NULL, "organizationId" uuid, CONSTRAINT "REL_c6e8ae55a4db3584686cbf6afe" UNIQUE ("organizationId"), CONSTRAINT "PK_88c8e2b461b711336c836b1e130" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c6e8ae55a4db3584686cbf6afe" ON "goal" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "post" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "postName" character varying NOT NULL, "divisionName" character varying NOT NULL DEFAULT 'Подразделение', "divisionNumber" integer NOT NULL, "parentId" uuid, "product" text NOT NULL, "purpose" text NOT NULL, "isDefault" boolean NOT NULL DEFAULT false, "isArchive" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "policyId" uuid, "organizationId" uuid, "accountId" uuid NOT NULL, "roleId" uuid, CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5c1cf55c308037b5aca1038a13" ON "post" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3517008f0c70943e789681270" ON "post" ("policyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_01d34b6e226affe884d75246ff" ON "post" ("organizationId") `);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying(50) NOT NULL, "lastName" character varying(50) NOT NULL, "middleName" character varying(50), "telegramId" integer, "telephoneNumber" character varying(13), "avatar_url" character varying, "vk_id" integer, "isFired" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "organizationId" uuid, "accountId" uuid, CONSTRAINT "UQ_6758e6c1db84e6f7e711f8021f5" UNIQUE ("telegramId"), CONSTRAINT "UQ_e8c530fb84a619fbff9941f31bb" UNIQUE ("telephoneNumber"), CONSTRAINT "UQ_da15f54aece694d1bf99b27d511" UNIQUE ("vk_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_68d3c22dbd95449360fdbf7a3f" ON "user" ("accountId") `);
        await queryRunner.query(`CREATE TYPE "public"."organization_reportday_enum" AS ENUM('1', '2', '3', '4', '5', '6', '0')`);
        await queryRunner.query(`CREATE TABLE "organization" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationName" character varying NOT NULL, "parentOrganizationId" uuid, "reportDay" "public"."organization_reportday_enum" NOT NULL DEFAULT '5', "colorCodes" hstore, "organizationColor" character varying(10), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "accountId" uuid NOT NULL, CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "account" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "accountName" character varying(120) NOT NULL, "tenantId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6d5184542539a16abc28d80084e" UNIQUE ("tenantId"), CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."convert_convertpath_enum" AS ENUM('Прямой', 'Согласование', 'Запрос')`);
        await queryRunner.query(`CREATE TYPE "public"."convert_converttype_enum" AS ENUM('Переписка', 'Приказ', 'Заявка')`);
        await queryRunner.query(`CREATE TABLE "convert" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "convertTheme" character varying(1024) NOT NULL, "pathOfPosts" uuid array, "convertPath" "public"."convert_convertpath_enum" NOT NULL, "convertType" "public"."convert_converttype_enum" NOT NULL, "convertStatus" boolean NOT NULL DEFAULT true, "activePostId" uuid, "dateStart" TIMESTAMP NOT NULL DEFAULT now(), "deadline" TIMESTAMP, "dateFinish" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "hostId" uuid NOT NULL, "accountId" uuid NOT NULL, CONSTRAINT "PK_ce49f01f9693806a247239d0504" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "watchers_to_convert" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "unreadMessagesCount" integer NOT NULL DEFAULT '0', "lastSeenNumber" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "convertId" uuid NOT NULL, "postId" uuid NOT NULL, CONSTRAINT "PK_1ef8dfa8b63aa69ec35be830253" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fileName" character varying(255) NOT NULL, "path" character varying NOT NULL, "size" integer NOT NULL, "mimetype" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "refresh_session" ADD CONSTRAINT "FK_3ae1d1221dbc787b1633dad301f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policy_directory" ADD CONSTRAINT "FK_2c1a0fcd287885bac0d8bc1eb02" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policy_to_policy_directory" ADD CONSTRAINT "FK_247be4c1647471cd372ca759a61" FOREIGN KEY ("policyId") REFERENCES "policy"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policy_to_policy_directory" ADD CONSTRAINT "FK_fa28233afa6009d479df0e2fbb9" FOREIGN KEY ("policyDirectoryId") REFERENCES "policy_directory"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "target_holder" ADD CONSTRAINT "FK_b5b7a1399bb79f0a6f817e26297" FOREIGN KEY ("targetId") REFERENCES "target"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "target_holder" ADD CONSTRAINT "FK_fe119993b527196cf2e85fd172b" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "objective" ADD CONSTRAINT "FK_3b9f2b0b950b992feb67e225e39" FOREIGN KEY ("strategyId") REFERENCES "strategy"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "objective" ADD CONSTRAINT "FK_e25ea3b661229ee317734f840b3" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "strategy" ADD CONSTRAINT "FK_8149a5eda5dca7f0700fc5f0894" FOREIGN KEY ("postCreatorId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "strategy" ADD CONSTRAINT "FK_27bc46cc455f581f0fa58b29f9f" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "strategy" ADD CONSTRAINT "FK_64a83d4b62181b7560b9a4907c6" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_0028dfadf312a1d7f51656c4a9a" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_b27ea5389a49df32d110a00b0fd" FOREIGN KEY ("strategyId") REFERENCES "strategy"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_8d691f8d69acef59f4ed3a872c4" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_95a0d2db82890455f82840563ba" FOREIGN KEY ("postCreatorId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_seen_status" ADD CONSTRAINT "FK_4f47e188f1bd628421d0f233327" FOREIGN KEY ("messageId") REFERENCES "message"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_seen_status" ADD CONSTRAINT "FK_1ff33fee84d2c7958ab60dbfad0" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_61fb800fdf4d052881ce8b1da29" FOREIGN KEY ("convertId") REFERENCES "convert"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_bc096b4e18b1f9508197cd98066" FOREIGN KEY ("senderId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachment_to_message" ADD CONSTRAINT "FK_13f0723c85fbc64fb393065df6d" FOREIGN KEY ("attachmentId") REFERENCES "attachment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachment_to_message" ADD CONSTRAINT "FK_f816633bad04a76f3a96495ddf3" FOREIGN KEY ("messageId") REFERENCES "message"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachment_to_target" ADD CONSTRAINT "FK_6aacb469923096e42216b9ba22a" FOREIGN KEY ("attachmentId") REFERENCES "attachment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachment_to_target" ADD CONSTRAINT "FK_0ebf12db8fd34879e66590fea2c" FOREIGN KEY ("targetId") REFERENCES "target"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "target" ADD CONSTRAINT "FK_c32ec30acb8104bda79376f3af4" FOREIGN KEY ("convertId") REFERENCES "convert"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "target" ADD CONSTRAINT "FK_b417a52ac7f5278f81327dfa86f" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "target" ADD CONSTRAINT "FK_1e4be9fdeee9449f164f5dc44b4" FOREIGN KEY ("policyId") REFERENCES "policy"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policy" ADD CONSTRAINT "FK_0a679332ddda27c77c914064144" FOREIGN KEY ("postCreatorId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policy" ADD CONSTRAINT "FK_7727efb9fd8b4ca0f8dd425698f" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policy" ADD CONSTRAINT "FK_77ba8d6f7aeefafedc654d025d2" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "statistic_data" ADD CONSTRAINT "FK_c511c5355fc7b012b7ee2097325" FOREIGN KEY ("statisticId") REFERENCES "statistic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "control_panel" ADD CONSTRAINT "FK_07c6f6f716c408b095dde2385b7" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "control_panel" ADD CONSTRAINT "FK_2efce09a10c55af81928255a706" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "panel_to_statistic" ADD CONSTRAINT "FK_7b4fbbcc0a5cb0fcb2d1041141d" FOREIGN KEY ("controlPanelId") REFERENCES "control_panel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "panel_to_statistic" ADD CONSTRAINT "FK_cc0da47767faed658adf3ed30dd" FOREIGN KEY ("statisticId") REFERENCES "statistic"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "statistic" ADD CONSTRAINT "FK_69ecb1c729c210beca6dba550db" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "statistic" ADD CONSTRAINT "FK_9c52f0fb9f943fef30e7d0b7a24" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "history_users_to_post" ADD CONSTRAINT "FK_f2d3568f244296ce211306dd244" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "history_users_to_post" ADD CONSTRAINT "FK_7541e4a4eb8305af0fc44012bed" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "convert_to_post" ADD CONSTRAINT "FK_24115eb24ec160fa1a07adbdbef" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "convert_to_post" ADD CONSTRAINT "FK_88fc2f96827f4d58ff1e86d6537" FOREIGN KEY ("convertId") REFERENCES "convert"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group" ADD CONSTRAINT "FK_c04a5c02d4950e967a37eaf1733" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_to_post" ADD CONSTRAINT "FK_c4f9121b07f10f2cf2f07beee5f" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_to_post" ADD CONSTRAINT "FK_7d84c384f4967eca67b658c339e" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_setting" ADD CONSTRAINT "FK_16d0b9882145d7d5a0cfa352a2d" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_setting" ADD CONSTRAINT "FK_18ed5a2a3c6b45e7cf94fb60b56" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goal" ADD CONSTRAINT "FK_6fd5b3818c6ebc92ef9ec4c3da3" FOREIGN KEY ("postCreatorId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goal" ADD CONSTRAINT "FK_45a4ad62e05e7e3997a0649c7ac" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goal" ADD CONSTRAINT "FK_c6e8ae55a4db3584686cbf6afe1" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_5c1cf55c308037b5aca1038a131" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_f3517008f0c70943e789681270b" FOREIGN KEY ("policyId") REFERENCES "policy"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_01d34b6e226affe884d75246ff2" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_f219a87fd8c020d3bb6527c9420" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_376552d942487d3c1953ad9304c" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_dfda472c0af7812401e592b6a61" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_68d3c22dbd95449360fdbf7a3f1" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_a1f50c955a5225aa6146bd38ead" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "convert" ADD CONSTRAINT "FK_5b57abe08f540888eaefac1c342" FOREIGN KEY ("hostId") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "convert" ADD CONSTRAINT "FK_92f0a21f1966cee5f74a004f1c5" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "watchers_to_convert" ADD CONSTRAINT "FK_79ed7ea972c5fd0304ec26a6b93" FOREIGN KEY ("convertId") REFERENCES "convert"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "watchers_to_convert" ADD CONSTRAINT "FK_3e780977eefdf98e496f90322a5" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "watchers_to_convert" DROP CONSTRAINT "FK_3e780977eefdf98e496f90322a5"`);
        await queryRunner.query(`ALTER TABLE "watchers_to_convert" DROP CONSTRAINT "FK_79ed7ea972c5fd0304ec26a6b93"`);
        await queryRunner.query(`ALTER TABLE "convert" DROP CONSTRAINT "FK_92f0a21f1966cee5f74a004f1c5"`);
        await queryRunner.query(`ALTER TABLE "convert" DROP CONSTRAINT "FK_5b57abe08f540888eaefac1c342"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_a1f50c955a5225aa6146bd38ead"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_68d3c22dbd95449360fdbf7a3f1"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_dfda472c0af7812401e592b6a61"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_376552d942487d3c1953ad9304c"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_f219a87fd8c020d3bb6527c9420"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_01d34b6e226affe884d75246ff2"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_f3517008f0c70943e789681270b"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_5c1cf55c308037b5aca1038a131"`);
        await queryRunner.query(`ALTER TABLE "goal" DROP CONSTRAINT "FK_c6e8ae55a4db3584686cbf6afe1"`);
        await queryRunner.query(`ALTER TABLE "goal" DROP CONSTRAINT "FK_45a4ad62e05e7e3997a0649c7ac"`);
        await queryRunner.query(`ALTER TABLE "goal" DROP CONSTRAINT "FK_6fd5b3818c6ebc92ef9ec4c3da3"`);
        await queryRunner.query(`ALTER TABLE "role_setting" DROP CONSTRAINT "FK_18ed5a2a3c6b45e7cf94fb60b56"`);
        await queryRunner.query(`ALTER TABLE "role_setting" DROP CONSTRAINT "FK_16d0b9882145d7d5a0cfa352a2d"`);
        await queryRunner.query(`ALTER TABLE "group_to_post" DROP CONSTRAINT "FK_7d84c384f4967eca67b658c339e"`);
        await queryRunner.query(`ALTER TABLE "group_to_post" DROP CONSTRAINT "FK_c4f9121b07f10f2cf2f07beee5f"`);
        await queryRunner.query(`ALTER TABLE "group" DROP CONSTRAINT "FK_c04a5c02d4950e967a37eaf1733"`);
        await queryRunner.query(`ALTER TABLE "convert_to_post" DROP CONSTRAINT "FK_88fc2f96827f4d58ff1e86d6537"`);
        await queryRunner.query(`ALTER TABLE "convert_to_post" DROP CONSTRAINT "FK_24115eb24ec160fa1a07adbdbef"`);
        await queryRunner.query(`ALTER TABLE "history_users_to_post" DROP CONSTRAINT "FK_7541e4a4eb8305af0fc44012bed"`);
        await queryRunner.query(`ALTER TABLE "history_users_to_post" DROP CONSTRAINT "FK_f2d3568f244296ce211306dd244"`);
        await queryRunner.query(`ALTER TABLE "statistic" DROP CONSTRAINT "FK_9c52f0fb9f943fef30e7d0b7a24"`);
        await queryRunner.query(`ALTER TABLE "statistic" DROP CONSTRAINT "FK_69ecb1c729c210beca6dba550db"`);
        await queryRunner.query(`ALTER TABLE "panel_to_statistic" DROP CONSTRAINT "FK_cc0da47767faed658adf3ed30dd"`);
        await queryRunner.query(`ALTER TABLE "panel_to_statistic" DROP CONSTRAINT "FK_7b4fbbcc0a5cb0fcb2d1041141d"`);
        await queryRunner.query(`ALTER TABLE "control_panel" DROP CONSTRAINT "FK_2efce09a10c55af81928255a706"`);
        await queryRunner.query(`ALTER TABLE "control_panel" DROP CONSTRAINT "FK_07c6f6f716c408b095dde2385b7"`);
        await queryRunner.query(`ALTER TABLE "statistic_data" DROP CONSTRAINT "FK_c511c5355fc7b012b7ee2097325"`);
        await queryRunner.query(`ALTER TABLE "policy" DROP CONSTRAINT "FK_77ba8d6f7aeefafedc654d025d2"`);
        await queryRunner.query(`ALTER TABLE "policy" DROP CONSTRAINT "FK_7727efb9fd8b4ca0f8dd425698f"`);
        await queryRunner.query(`ALTER TABLE "policy" DROP CONSTRAINT "FK_0a679332ddda27c77c914064144"`);
        await queryRunner.query(`ALTER TABLE "target" DROP CONSTRAINT "FK_1e4be9fdeee9449f164f5dc44b4"`);
        await queryRunner.query(`ALTER TABLE "target" DROP CONSTRAINT "FK_b417a52ac7f5278f81327dfa86f"`);
        await queryRunner.query(`ALTER TABLE "target" DROP CONSTRAINT "FK_c32ec30acb8104bda79376f3af4"`);
        await queryRunner.query(`ALTER TABLE "attachment_to_target" DROP CONSTRAINT "FK_0ebf12db8fd34879e66590fea2c"`);
        await queryRunner.query(`ALTER TABLE "attachment_to_target" DROP CONSTRAINT "FK_6aacb469923096e42216b9ba22a"`);
        await queryRunner.query(`ALTER TABLE "attachment_to_message" DROP CONSTRAINT "FK_f816633bad04a76f3a96495ddf3"`);
        await queryRunner.query(`ALTER TABLE "attachment_to_message" DROP CONSTRAINT "FK_13f0723c85fbc64fb393065df6d"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_bc096b4e18b1f9508197cd98066"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_61fb800fdf4d052881ce8b1da29"`);
        await queryRunner.query(`ALTER TABLE "message_seen_status" DROP CONSTRAINT "FK_1ff33fee84d2c7958ab60dbfad0"`);
        await queryRunner.query(`ALTER TABLE "message_seen_status" DROP CONSTRAINT "FK_4f47e188f1bd628421d0f233327"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_95a0d2db82890455f82840563ba"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_8d691f8d69acef59f4ed3a872c4"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_b27ea5389a49df32d110a00b0fd"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_0028dfadf312a1d7f51656c4a9a"`);
        await queryRunner.query(`ALTER TABLE "strategy" DROP CONSTRAINT "FK_64a83d4b62181b7560b9a4907c6"`);
        await queryRunner.query(`ALTER TABLE "strategy" DROP CONSTRAINT "FK_27bc46cc455f581f0fa58b29f9f"`);
        await queryRunner.query(`ALTER TABLE "strategy" DROP CONSTRAINT "FK_8149a5eda5dca7f0700fc5f0894"`);
        await queryRunner.query(`ALTER TABLE "objective" DROP CONSTRAINT "FK_e25ea3b661229ee317734f840b3"`);
        await queryRunner.query(`ALTER TABLE "objective" DROP CONSTRAINT "FK_3b9f2b0b950b992feb67e225e39"`);
        await queryRunner.query(`ALTER TABLE "target_holder" DROP CONSTRAINT "FK_fe119993b527196cf2e85fd172b"`);
        await queryRunner.query(`ALTER TABLE "target_holder" DROP CONSTRAINT "FK_b5b7a1399bb79f0a6f817e26297"`);
        await queryRunner.query(`ALTER TABLE "policy_to_policy_directory" DROP CONSTRAINT "FK_fa28233afa6009d479df0e2fbb9"`);
        await queryRunner.query(`ALTER TABLE "policy_to_policy_directory" DROP CONSTRAINT "FK_247be4c1647471cd372ca759a61"`);
        await queryRunner.query(`ALTER TABLE "policy_directory" DROP CONSTRAINT "FK_2c1a0fcd287885bac0d8bc1eb02"`);
        await queryRunner.query(`ALTER TABLE "refresh_session" DROP CONSTRAINT "FK_3ae1d1221dbc787b1633dad301f"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP TABLE "watchers_to_convert"`);
        await queryRunner.query(`DROP TABLE "convert"`);
        await queryRunner.query(`DROP TYPE "public"."convert_converttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."convert_convertpath_enum"`);
        await queryRunner.query(`DROP TABLE "account"`);
        await queryRunner.query(`DROP TABLE "organization"`);
        await queryRunner.query(`DROP TYPE "public"."organization_reportday_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68d3c22dbd95449360fdbf7a3f"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01d34b6e226affe884d75246ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3517008f0c70943e789681270"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c1cf55c308037b5aca1038a13"`);
        await queryRunner.query(`DROP TABLE "post"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6e8ae55a4db3584686cbf6afe"`);
        await queryRunner.query(`DROP TABLE "goal"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TYPE "public"."role_rolename_enum"`);
        await queryRunner.query(`DROP TABLE "role_setting"`);
        await queryRunner.query(`DROP TYPE "public"."role_setting_module_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d84c384f4967eca67b658c339"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4f9121b07f10f2cf2f07beee5"`);
        await queryRunner.query(`DROP TABLE "group_to_post"`);
        await queryRunner.query(`DROP TABLE "group"`);
        await queryRunner.query(`DROP TABLE "convert_to_post"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2d3568f244296ce211306dd24"`);
        await queryRunner.query(`DROP TABLE "history_users_to_post"`);
        await queryRunner.query(`DROP TABLE "statistic"`);
        await queryRunner.query(`DROP TYPE "public"."statistic_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b4fbbcc0a5cb0fcb2d1041141"`);
        await queryRunner.query(`DROP TABLE "panel_to_statistic"`);
        await queryRunner.query(`DROP TABLE "control_panel"`);
        await queryRunner.query(`DROP TYPE "public"."control_panel_graphtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."control_panel_paneltype_enum"`);
        await queryRunner.query(`DROP TABLE "statistic_data"`);
        await queryRunner.query(`DROP TYPE "public"."statistic_data_correlationtype_enum"`);
        await queryRunner.query(`DROP TABLE "policy"`);
        await queryRunner.query(`DROP TYPE "public"."policy_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."policy_state_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e4be9fdeee9449f164f5dc44b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b417a52ac7f5278f81327dfa86"`);
        await queryRunner.query(`DROP TABLE "target"`);
        await queryRunner.query(`DROP TYPE "public"."target_targetstate_enum"`);
        await queryRunner.query(`DROP TYPE "public"."target_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ebf12db8fd34879e66590fea2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6aacb469923096e42216b9ba22"`);
        await queryRunner.query(`DROP TABLE "attachment_to_target"`);
        await queryRunner.query(`DROP TABLE "attachment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f816633bad04a76f3a96495ddf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13f0723c85fbc64fb393065df6"`);
        await queryRunner.query(`DROP TABLE "attachment_to_message"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP TABLE "message_seen_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b27ea5389a49df32d110a00b0f"`);
        await queryRunner.query(`DROP TABLE "project"`);
        await queryRunner.query(`DROP TYPE "public"."project_type_enum"`);
        await queryRunner.query(`DROP TABLE "strategy"`);
        await queryRunner.query(`DROP TYPE "public"."strategy_state_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b9f2b0b950b992feb67e225e3"`);
        await queryRunner.query(`DROP TABLE "objective"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe119993b527196cf2e85fd172"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5b7a1399bb79f0a6f817e2629"`);
        await queryRunner.query(`DROP TABLE "target_holder"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_247be4c1647471cd372ca759a6"`);
        await queryRunner.query(`DROP TABLE "policy_to_policy_directory"`);
        await queryRunner.query(`DROP TABLE "policy_directory"`);
        await queryRunner.query(`DROP TABLE "refresh_session"`);
    }

}
